### ISSUE TITLE
Issue in Homework 9

### ISSUE THREAD

**Issue by vmtenorio** [ali-tny/boyd-convex-optimisation-py#1]
Hi!

First of all, I wanted to thank you for the amazing work with these notebooks and for the fact that you bothered to upload it publicly. Shame I only discovered your repository when facing the last homework of the course! But for that one it helped me a lot!

I just wanted to point out an issue I found with the code for the "Question 3: Allocation of interdiction effort" in homework 9 notebook. When setting up the constraints, you set `z[0] == 1`, as if it was a probability. In fact, you need to set it up to 0, as `z` is the log of a probability, and $\log 1 = 0$.

Also, and as a minor correction, in the last equation of the markdown block you missed a `-` sign: $\ldots z_i - z_j \geq - a_{ij} x_{ij} \ldots$.

Let me know if you want me to open a pull request for this.

Thanks again for your amazing work! Keep it up!

**Comment by ali-tny** [comment]
Hi!

I'm so glad it was useful for you, even if just for the last homework! I suppose you are now a master at translating MATLAB arrays into numpy too, heh heh. Congrats on finishing the course!

Thanks for your keen eye spotting those mistakes - of course if you have time to make a PR I'd be v glad to take your corrections! 

merry Christmas ☃️

**Comment by ali-tny** [comment]
fixed by https://github.com/ali-tny/boyd-convex-optimisation-py/pull/2
